default:
  observable:
    observable-default:
      plugin: observable-default
      enabled: true
      config: {}
  events:
    events-default:
      plugin: events-default
      enabled: true
  services:
    service-betterportal-docs-site:
      plugin: service-betterportal-docs-site
      enabled: true
      config:
        host: 0.0.0.0
        port: 3400
        bpConfigPath: ../../../bp-config.yaml
        configApiToken: bp-dev-config-token
        configEncryptionKey: bp-dev-encryption-key-min16chars
