default:
  observable:
    observable-default:
      plugin: observable-default
      enabled: true
      config: {}
  events:
    events-default:
      plugin: events-default
      enabled: true
  services:
    service-betterportal-hello-view:
      plugin: service-betterportal-hello-view
      enabled: true
      config: {}
