default:
  observable:
    observable-default:
      plugin: observable-default
      enabled: true
      config: {}
  events:
    events-default:
      plugin: events-default
      enabled: true
  services:
    service-betterportal-theme-embedded:
      plugin: service-betterportal-theme-embedded
      enabled: true
      config:
        host: 0.0.0.0
        port: 3110
        betterportal: {}
